### ISSUE TITLE
Release tags are not being applied correctly

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-pathpoint#35]
### References

PR: https://github.com/newrelic/nr1-pathpoint/pull/34
failed action: https://github.com/newrelic/nr1-pathpoint/actions/runs/1758312693

### Issue 
When attempting to update the version of the application in the package.json file, the version is not bumping correctly and the release job is failing on the error:

```
Error: Command failed with exit code 128: git tag v1.0.0 682bac8d79ea7ad61adbea9879c73f4728e68099
fatal: tag 'v1.0.0' already exists
    at makeError (/home/runner/.npm/_npx/1684/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/.npm/_npx/1684/lib/node_modules/semantic-release/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async tag (/home/runner/.npm/_npx/1684/lib/node_modules/semantic-release/lib/git.js:224:3)
    at async run (/home/runner/.npm/_npx/1684/lib/node_modules/semantic-release/index.js:191:5)
    at async module.exports (/home/runner/.npm/_npx/1684/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/runner/.npm/_npx/1684/lib/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag v1.0.0 682bac8d79ea7ad61adbea9879c73f4728e68099',
  command: 'git tag v1.0.0 682bac8d79ea7ad61adbea9879c73f4728e68099',
  escapedCommand: 'git tag v1.0.0 682bac8d79ea7ad61adbea9879c73f4728e68099',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: tag 'v1.0.0' already exists",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```

### Expected 

The release job runs successfully and the version changes

**Comment by jpvajda** [comment]
@LizBaker was able to figure this out. 💯

**Comment by LizBaker** [comment]
The commits on version 1.5.4 were rebased at some point and because of this all of their SHAs were regenerated. This made the commit that had the 1.5.4 tag an orphan that didn't exist on the repo. Semantic release didn't like that and decided there was no version history and kept trying to version at 1.0.0.
We tagged the correct commit with 1.5.4 and deleted the old 1.5.4 tag/release and now 1.5.5 has succeeded with the most recent work. it should continue to work 🤞
